language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
script:
    - python -m unittest discover -s tests/
notifications:
  email:
      on_success: change
      on_failure: change