language: python
python:
    - 3.6
install:
    - pip install -r requirements/requirements_prod.txt
before_script:
    - pylint graphs repair nodes 
script:
    - coverage run --source='.' -m unittest discover -s tests/
after_script:
    - codecov
notifications:
  email:
      on_success: change
      on_failure: change
